# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mashape_key: <%= ENV["MASHAPE_KEY"] %>
  omniauth:
      facebook:
          key: <%= ENV["FACEBOOK_APP_ID"] %>
          secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
      github:
          key: <%= ENV["GITHUB_APP_ID"] %>
          secret: <%= ENV["GITHUB_APP_SECRET"] %>
      google_oauth2:
          key: <%= ENV["GOOGLE_OAUTH2_APP_ID"] %>
          secret: <%= ENV["GOOGLE_OAUTH2_APP_SECRET"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mashape_key: <%= ENV["MASHAPE_KEY"] %>
  omniauth:
      facebook:
          key: <%= ENV["FACEBOOK_APP_ID"] %>
          secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
      github:
          key: <%= ENV["GITHUB_APP_ID"] %>
          secret: <%= ENV["GITHUB_APP_SECRET"] %>
      google_oauth2:
          key: <%= ENV["GOOGLE_OAUTH2_APP_ID"] %>
          secret: <%= ENV["GOOGLE_OAUTH2_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mashape_key: <%= ENV["MASHAPE_KEY"] %>
  omniauth:
      facebook:
          key: <%= ENV["FACEBOOK_APP_ID"] %>
          secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
      github:
          key: <%= ENV["GITHUB_APP_ID"] %>
          secret: <%= ENV["GITHUB_APP_SECRET"] %>
      google_oauth2:
          key: <%= ENV["GOOGLE_OAUTH2_APP_ID"] %>
          secret: <%= ENV["GOOGLE_OAUTH2_APP_SECRET"] %>
